export enum RoleEnum {
    ADMIN_USER = 'ADMIN_USER',
    COMPANY_USER = 'COMPANY_USER'
}

export enum OrderEventTypeValues {
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_PAYMENT_COMPLETED = 'ORDER_PAYMENT_COMPLETED',
    ORDER_REJECTED = 'ORDER_REJECTED',
    ORDER_CANCELED = 'ORDER_CANCELED',
    ORDER_CANCELED_BY_USER = 'ORDER_CANCELED_BY_USER'
}
